FROM python:3.10-slim-buster

WORKDIR /code

COPY ./apirequirements.txt /code/apirequirements.txt
RUN pip install --no-cache-dir -r /code/apirequirements.txt

# Copying your application code
COPY . /code

# Command to run your application
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "main:app"]
