FROM python:3.10-slim-buster

WORKDIR /app

COPY celeryrequirements.txt .

RUN pip install --no-cache-dir -r celeryrequirements.txt

COPY . .

CMD ["celery", "-A", "celery_trainer", "worker", "--loglevel=info", "--uid=nobody", "--gid=nogroup"]