FROM python:3.10-slim-buster

WORKDIR /code

COPY ./celeryrequirements.txt /code/celeryrequirements.txt
RUN pip install --no-cache-dir -r /code/celeryrequirements.txt

COPY . /code

CMD [ "python", "euro.py"]