version: '3.3'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    restart: always
    volumes:
      - 'redis_volume_data:/data'
  dataservice:
    build:
      context: dataservice
    ports:
      - '3000:3000'
    depends_on:
      - service-discovery
  service-discovery:
    build:
      context: servicediscovery
    ports:
      - '8000:8000'
  trainservice:
    build:
      context: trainservice
      dockerfile: Dockerfile.api
    ports:
      - '1234:1234'
    depends_on:
      - service-discovery
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 200M
  celery-trainer:
    build:
      context: trainservice
      dockerfile: Dockerfile.celery
    depends_on:
      - trainservice
      - redis
  predservice:
    build:
      context: predservice
      dockerfile: Dockerfile.api
    depends_on:
      - service-discovery
    ports:
      - '8080:8080'
  lpg-celery:
    build:
      context: predservice
      dockerfile: Dockerfile.lpg
    depends_on:
      - predservice
  diesel-celery:
    build:
      context: predservice
      dockerfile: Dockerfile.diesel
    depends_on:
      - predservice
  euro-celery:
    build:
      context: predservice
      dockerfile: Dockerfile.euro
    depends_on:
      - predservice
  mlflow-db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: mlflowdb
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: password
    ports:
      - '5436:5432'
  mlflow-server:
    build:
      context: ../mlflow_server/src/mlflow/
      dockerfile: Dockerfile
    container_name: mlflow_server
    environment:
      AWS_REGION: eu-west-3
      AWS_DEFAULT_REGION: eu-west-3
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: adminadmin
      MLFLOW_S3_ENDPOINT_URL: 'http://minio:9000'
    ports:
      - '5000:5000'
    command: >-
      mlflow server --host 0.0.0.0 --workers 1 --backend-store-uri
      postgresql://mlflow:password@mlflow-db:5432/mlflowdb
      --default-artifact-root s3://test-bucket/
  minio:
    image: 'minio/minio:RELEASE.2023-12-23T07-19-11Z'
    command: 'server /data --console-address ":9001"'
    ports:
      - '9020:9000'
      - '9021:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
      MINIO_SITE_REGION: eu-west-3
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " echo sleep 30; sleep 30; /usr/bin/mc config host add myminio
      http://minio:9000 admin adminadmin; /usr/bin/mc mb myminio/test-bucket;
      exit 0; "
volumes:
  redis_volume_data: null
  localstack-vol: null
